package com.ebizprise.winw.project.entity;
// Generated 2020/5/7 下午 05:35:55 by Hibernate Tools 4.0.0

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.ebizprise.winw.project.base.entity.BaseEntity;

/**
 * DashboardDirectAuth generated by hbm2java
 */
@Entity
@Table(name = "DASHBOARD_DIRECT_AUTH")
public class DashboardDirectAuthEntity extends BaseEntity {

    private Long id;
    private String userId;
    private String division;
    private String updatedBy;
    private Date updatedAt;
    private String createdBy;
    private Date createdAt;

    public DashboardDirectAuthEntity() {
    }

    public DashboardDirectAuthEntity(Long id, String userId, String division) {
        this.id = id;
        this.userId = userId;
        this.division = division;
    }

    public DashboardDirectAuthEntity(Long id, String userId, String division, String updatedBy,
            Date updatedAt, String createdBy, Date createdAt) {
        this.id = id;
        this.userId = userId;
        this.division = division;
        this.updatedBy = updatedBy;
        this.updatedAt = updatedAt;
        this.createdBy = createdBy;
        this.createdAt = createdAt;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "Id", unique = true, nullable = false)
    public Long getId () {
        return this.id;
    }

    public void setId (Long id) {
        this.id = id;
    }

    @Column(name = "UserId", unique = true, nullable = false)
    public String getUserId () {
        return this.userId;
    }

    public void setUserId (String userId) {
        this.userId = userId;
    }

    @Column(name = "Division", nullable = false)
    public String getDivision () {
        return this.division;
    }

    public void setDivision (String division) {
        this.division = division;
    }

    @Override
    @Column(name = "UpdatedBy")
    public String getUpdatedBy () {
        return this.updatedBy;
    }

    @Override
    public void setUpdatedBy (String updatedBy) {
        this.updatedBy = updatedBy;
    }

    @Override
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "UpdatedAt", length = 23)
    public Date getUpdatedAt () {
        return this.updatedAt;
    }

    @Override
    public void setUpdatedAt (Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    @Override
    @Column(name = "CreatedBy")
    public String getCreatedBy () {
        return this.createdBy;
    }

    @Override
    public void setCreatedBy (String createdBy) {
        this.createdBy = createdBy;
    }

    @Override
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "CreatedAt", length = 23)
    public Date getCreatedAt () {
        return this.createdAt;
    }

    @Override
    public void setCreatedAt (Date createdAt) {
        this.createdAt = createdAt;
    }

}
