package com.ebizprise.winw.project.entity;
// Generated 2019/9/21 下午 12:33:06 by Hibernate Tools 4.0.0

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.ebizprise.winw.project.base.entity.BaseEntity;

/**
 * FormJobInfoDate generated by hbm2java
 */
@Entity
@Table(name = "FORM_JOB_INFO_DATE")
public class FormJobInfoDateEntity extends BaseEntity {

    private Long id;
    private String formId;
    private Date offLineTime;
    private Date mect;
    private Date eot;
    private Date ect;
    private Date ast;
    private Date act;
    private Date cat;
    private Date cct;
    private Date ist;
    private Date ict;
    private Date tct;
    private Date sct;
    private Date sit;
    private String isPlaning;
    private String isUnPlaning;

    public FormJobInfoDateEntity() {
    }

    public FormJobInfoDateEntity(Long id, String formId) {
        this.id = id;
        this.formId = formId;
    }

    public FormJobInfoDateEntity(Long id, String formId, Date offLineTime, Date mect, Date eot, Date ect, Date ast,
            Date act, Date cat, Date cct, Date ist, Date ict, Date tct, Date sct, Date sit, String isPlaning,
            String isUnPlaning, String updatedBy, Date updatedAt, String createdBy, Date createdAt) {
        this.id = id;
        this.formId = formId;
        this.offLineTime = offLineTime;
        this.mect = mect;
        this.eot = eot;
        this.ect = ect;
        this.ast = ast;
        this.act = act;
        this.cat = cat;
        this.cct = cct;
        this.ist = ist;
        this.ict = ict;
        this.tct = tct;
        this.sct = sct;
        this.sit = sit;
        this.isPlaning = isPlaning;
        this.isUnPlaning = isUnPlaning;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "Id", unique = true, nullable = false)
    public Long getId () {
        return this.id;
    }

    public void setId (Long id) {
        this.id = id;
    }

    @Column(name = "FormId", unique = true, nullable = false)
    public String getFormId () {
        return this.formId;
    }

    public void setFormId (String formId) {
        this.formId = formId;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "OffLineTime", length = 23)
    public Date getOffLineTime () {
        return this.offLineTime;
    }

    public void setOffLineTime (Date offLineTime) {
        this.offLineTime = offLineTime;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "MECT", length = 23)
    public Date getMect () {
        return this.mect;
    }

    public void setMect (Date mect) {
        this.mect = mect;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "EOT", length = 23)
    public Date getEot () {
        return this.eot;
    }

    public void setEot (Date eot) {
        this.eot = eot;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "ECT", length = 23)
    public Date getEct () {
        return this.ect;
    }

    public void setEct (Date ect) {
        this.ect = ect;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "AST", length = 23)
    public Date getAst () {
        return this.ast;
    }

    public void setAst (Date ast) {
        this.ast = ast;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "ACT", length = 23)
    public Date getAct () {
        return this.act;
    }

    public void setAct (Date act) {
        this.act = act;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "CAT", length = 23)
    public Date getCat () {
        return this.cat;
    }

    public void setCat (Date cat) {
        this.cat = cat;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "CCT", length = 23)
    public Date getCct () {
        return this.cct;
    }

    public void setCct (Date cct) {
        this.cct = cct;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "IST", length = 23)
    public Date getIst () {
        return this.ist;
    }

    public void setIst (Date ist) {
        this.ist = ist;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "ICT", length = 23)
    public Date getIct () {
        return this.ict;
    }

    public void setIct (Date ict) {
        this.ict = ict;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "TCT", length = 23)
    public Date getTct () {
        return this.tct;
    }

    public void setTct (Date tct) {
        this.tct = tct;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "SCT", length = 23)
    public Date getSct () {
        return this.sct;
    }

    public void setSct (Date sct) {
        this.sct = sct;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "SIT", length = 23)
    public Date getSit () {
        return this.sit;
    }

    public void setSit (Date sit) {
        this.sit = sit;
    }

    @Column(name = "IsPlaning", length = 1)
    public String getIsPlaning () {
        return this.isPlaning;
    }

    public void setIsPlaning (String isPlaning) {
        this.isPlaning = isPlaning;
    }

    @Column(name = "IsUnPlaning", length = 1)
    public String getIsUnPlaning () {
        return this.isUnPlaning;
    }

    public void setIsUnPlaning (String isUnPlaning) {
        this.isUnPlaning = isUnPlaning;
    }

}
