package com.ebizprise.winw.project.entity;
// Generated 2019/8/30 下午 02:45:36 by Hibernate Tools 4.0.0

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.ebizprise.winw.project.base.entity.BaseEntity;

/**
 * FormJobCountersigned generated by hbm2java
 */
@Entity
@Table(name = "FORM_JOB_COUNTERSIGNED")
public class FormJobCountersignedEntity extends BaseEntity {

    private Long id;
    private String formId;
    private String division;
    private String dataType;
    private String userId;
    private String bookNumber;
    private String onlyNumber;
    private String onlyCode;
    private String linkNumber;
    private String linkCode;
    private String linkOnlyNumber;
    private String rollbackDesc;
    private Date tct;
    private Date sct;
    private Date sit;
    private String isTest;
    private String isRollback;
    private String isProduction;
    private String book;
    private String only;
    private String link;
    private String other;
    private String linkOnly;
    private String description;

    public FormJobCountersignedEntity() {
    }

    public FormJobCountersignedEntity(Long id, String formId, String division) {
        this.id = id;
        this.formId = formId;
        this.division = division;
    }

    public FormJobCountersignedEntity(Long id, String formId, String division, String dataType, String userId,
            String bookNumber, String onlyNumber, String onlyCode, String linkNumber, String linkCode,
            String linkOnlyNumber, String rollbackDesc, Date tct, Date sct, Date sit, String isTest,
            String isRollback, String isProduction, String book, String only, String link, String other,
            String linkOnly, String description, String updatedBy, Date updatedAt, String createdBy,
            Date createdAt) {
        this.id = id;
        this.formId = formId;
        this.division = division;
        this.dataType = dataType;
        this.userId = userId;
        this.bookNumber = bookNumber;
        this.onlyNumber = onlyNumber;
        this.onlyCode = onlyCode;
        this.linkNumber = linkNumber;
        this.linkCode = linkCode;
        this.linkOnlyNumber = linkOnlyNumber;
        this.rollbackDesc = rollbackDesc;
        this.tct = tct;
        this.sct = sct;
        this.sit = sit;
        this.isTest = isTest;
        this.isRollback = isRollback;
        this.isProduction = isProduction;
        this.book = book;
        this.only = only;
        this.link = link;
        this.other = other;
        this.linkOnly = linkOnly;
        this.description = description;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "Id", unique = true, nullable = false)
    public Long getId () {
        return this.id;
    }

    public void setId (Long id) {
        this.id = id;
    }

    @Column(name = "FormId", unique = true, nullable = false)
    public String getFormId () {
        return this.formId;
    }

    public void setFormId (String formId) {
        this.formId = formId;
    }

    @Column(name = "division", nullable = false)
    public String getDivision () {
        return this.division;
    }

    public void setDivision (String division) {
        this.division = division;
    }

    @Column(name = "DataType")
    public String getDataType () {
        return this.dataType;
    }

    public void setDataType (String dataType) {
        this.dataType = dataType;
    }

    @Column(name = "UserId")
    public String getUserId () {
        return this.userId;
    }

    public void setUserId (String userId) {
        this.userId = userId;
    }

    @Column(name = "BookNumber")
    public String getBookNumber () {
        return this.bookNumber;
    }

    public void setBookNumber (String bookNumber) {
        this.bookNumber = bookNumber;
    }

    @Column(name = "OnlyNumber")
    public String getOnlyNumber () {
        return this.onlyNumber;
    }

    public void setOnlyNumber (String onlyNumber) {
        this.onlyNumber = onlyNumber;
    }

    @Column(name = "OnlyCode")
    public String getOnlyCode () {
        return this.onlyCode;
    }

    public void setOnlyCode (String onlyCode) {
        this.onlyCode = onlyCode;
    }

    @Column(name = "LinkNumber")
    public String getLinkNumber () {
        return this.linkNumber;
    }

    public void setLinkNumber (String linkNumber) {
        this.linkNumber = linkNumber;
    }

    @Column(name = "LinkCode")
    public String getLinkCode () {
        return this.linkCode;
    }

    public void setLinkCode (String linkCode) {
        this.linkCode = linkCode;
    }

    @Column(name = "LinkOnlyNumber")
    public String getLinkOnlyNumber () {
        return this.linkOnlyNumber;
    }

    public void setLinkOnlyNumber (String linkOnlyNumber) {
        this.linkOnlyNumber = linkOnlyNumber;
    }

    @Column(name = "RollbackDesc")
    public String getRollbackDesc() {
        return rollbackDesc;
    }

    public void setRollbackDesc(String rollbackDesc) {
        this.rollbackDesc = rollbackDesc;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "TCT", length = 23)
    public Date getTct () {
        return this.tct;
    }

    public void setTct (Date tct) {
        this.tct = tct;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "SCT", length = 23)
    public Date getSct () {
        return this.sct;
    }

    public void setSct (Date sct) {
        this.sct = sct;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "SIT", length = 23)
    public Date getSit () {
        return this.sit;
    }

    public void setSit (Date sit) {
        this.sit = sit;
    }

    @Column(name = "IsTest", length = 1)
    public String getIsTest () {
        return this.isTest;
    }

    public void setIsTest (String isTest) {
        this.isTest = isTest;
    }

    @Column(name = "IsRollback", length = 1)
    public String getIsRollback () {
        return this.isRollback;
    }

    public void setIsRollback (String isRollback) {
        this.isRollback = isRollback;
    }

    @Column(name = "IsProduction", length = 1)
    public String getIsProduction () {
        return this.isProduction;
    }

    public void setIsProduction (String isProduction) {
        this.isProduction = isProduction;
    }

    @Column(name = "Book")
    public String getBook () {
        return this.book;
    }

    public void setBook (String book) {
        this.book = book;
    }

    @Column(name = "Only")
    public String getOnly () {
        return this.only;
    }

    public void setOnly (String only) {
        this.only = only;
    }

    @Column(name = "Link")
    public String getLink () {
        return this.link;
    }

    public void setLink (String link) {
        this.link = link;
    }

    @Column(name = "Other")
    public String getOther () {
        return this.other;
    }

    public void setOther (String other) {
        this.other = other;
    }

    @Column(name = "LinkOnly")
    public String getLinkOnly () {
        return this.linkOnly;
    }

    public void setLinkOnly (String linkOnly) {
        this.linkOnly = linkOnly;
    }

    @Column(name = "Description")
    public String getDescription () {
        return this.description;
    }

    public void setDescription (String description) {
        this.description = description;
    }

}
