package com.ebizprise.winw.project.entity;
// Generated 2020/6/5 下午 01:34:10 by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import com.ebizprise.winw.project.base.entity.BaseEntity;

/**
 * FormJobSegmentList generated by hbm2java
 */
@Entity
@Table(name = "FORM_JOB_SEGMENT_LIST")
public class FormJobSegmentListEntity extends BaseEntity {

    private Long id;
    private String formId;
    private String type;
    private String segment;
    private String keyValue;
    private String alterColumns;
    private String alterContent;
    private String layoutDataset;

    public FormJobSegmentListEntity() {
    }

    public FormJobSegmentListEntity(Long id, String formId) {
        this.id = id;
        this.formId = formId;
    }

    public FormJobSegmentListEntity(Long id, String formId, String segment, String keyValue, String alterColumns,
            String alterContent, String layoutDataset, String updatedBy, Date updatedAt, String createdBy,
            Date createdAt, String type) {
        this.id = id;
        this.formId = formId;
        this.segment = segment;
        this.keyValue = keyValue;
        this.alterColumns = alterColumns;
        this.alterContent = alterContent;
        this.layoutDataset = layoutDataset;
        this.type = type;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "Id", unique = true, nullable = false)
    public Long getId () {
        return this.id;
    }

    public void setId (Long id) {
        this.id = id;
    }

    @Column(name = "FormId", nullable = false)
    public String getFormId () {
        return this.formId;
    }

    public void setFormId (String formId) {
        this.formId = formId;
    }

    @Column(name = "Segment")
    public String getSegment () {
        return this.segment;
    }

    public void setSegment (String segment) {
        this.segment = segment;
    }

    @Column(name = "KeyValue")
    public String getKeyValue () {
        return this.keyValue;
    }

    public void setKeyValue (String keyValue) {
        this.keyValue = keyValue;
    }

    @Column(name = "AlterColumns")
    public String getAlterColumns () {
        return this.alterColumns;
    }

    public void setAlterColumns (String alterColumns) {
        this.alterColumns = alterColumns;
    }

    @Column(name = "AlterContent")
    public String getAlterContent () {
        return this.alterContent;
    }

    public void setAlterContent (String alterContent) {
        this.alterContent = alterContent;
    }

    @Column(name = "LayoutDataset")
    public String getLayoutDataset () {
        return this.layoutDataset;
    }

    public void setLayoutDataset (String layoutDataset) {
        this.layoutDataset = layoutDataset;
    }

    @Column(name = "Type")
    public String getType () {
        return type;
    }

    public void setType (String type) {
        this.type = type;
    }

}
