package com.ebizprise.winw.project.entity;
// Generated 2019/8/30 下午 01:55:06 by Hibernate Tools 4.0.0

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

import com.ebizprise.winw.project.base.entity.BaseEntity;

/**
 * FormFile generated by hbm2java
 */
@Entity
@Table(name = "FORM_FILE")
public class FormFileEntity extends BaseEntity {

    private Long id;
    private String formId;
    private String name;
    private String description;
    private String alterContent;
    private String layoutDataset;
    private byte[] data;
    private String islocked;
    private String type;

    public FormFileEntity() {
    }

    public FormFileEntity(Long id) {
        this.id = id;
    }

    public FormFileEntity(Long id, String formId, String name, String description, String alterCotent,
            String layoutDataset, byte[] data, String updatedBy, Date updatedAt, String createdBy,
            Date createdAt,String islocked,String type) {
        this.id = id;
        this.formId = formId;
        this.name = name;
        this.description = description;
        this.alterContent = alterCotent;
        this.layoutDataset = layoutDataset;
        this.data = data;
        this.islocked = islocked;
        this.type = type;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "Id", unique = true, nullable = false)
    public Long getId () {
        return this.id;
    }

    public void setId (Long id) {
        this.id = id;
    }

    @Column(name = "FormId", length = 20)
    public String getFormId () {
        return this.formId;
    }

    public void setFormId (String formId) {
        this.formId = formId;
    }

    @Column(name = "Name")
    public String getName () {
        return this.name;
    }

    public void setName (String name) {
        this.name = name;
    }

    @Column(name = "Description")
    public String getDescription () {
        return this.description;
    }

    public void setDescription (String description) {
        this.description = description;
    }

    @Column(name = "AlterContent")
    public String getAlterContent () {
        return this.alterContent;
    }

    public void setAlterContent (String alterCotent) {
        this.alterContent = alterCotent;
    }

    @Column(name = "LayoutDataset")
    public String getLayoutDataset () {
        return this.layoutDataset;
    }

    public void setLayoutDataset (String layoutDataset) {
        this.layoutDataset = layoutDataset;
    }

    @Column(name = "Data")
    public byte[] getData () {
        return this.data;
    }

    public void setData (byte[] data) {
        this.data = data;
    }

    @Column(name = "Islocked")
    public String getIslocked() {
        return islocked;
    }

    public void setIslocked(String islocked) {
        this.islocked = islocked;
    }

    @Column(name = "Type")
    public String getType () {
        return type;
    }

    public void setType (String type) {
        this.type = type;
    }

}
