package com.ebizprise.winw.project.entity;
// Generated 2019/9/21 下午 12:33:06 by Hibernate Tools 4.0.0

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.ebizprise.winw.project.base.entity.BaseEntity;

/**
 * FormJobInfoSysDetail generated by hbm2java
 */
@Entity
@Table(name = "FORM_JOB_INFO_SYS_DETAIL")
public class FormJobInfoSysDetailEntity extends BaseEntity {

    private Long id;
    private String formId;
    private String working;
    private String status;
    private String cCategory;
    private String cClass;
    private String cComponent;
    private String systemId;
    private String system;
    private String userId;
    private String cuserId;
    private String astatus;
    private Date ect;
    private Date onLineTime;
    private Date offLineTime;
    private String isReset;
    private String isProduction;
    private String isTest;
    private String isHandleFirst;
    private String isForward;
    private String isInterrupt;
    private String summary;
    private String purpose;
    private String content;
    private String effectScope;
    private String remark;
    private String reset;
    private String countersigneds;
    private String spcGroups;

    public FormJobInfoSysDetailEntity() {
    }

    public FormJobInfoSysDetailEntity(Long id, String formId) {
        this.id = id;
        this.formId = formId;
    }

    public FormJobInfoSysDetailEntity(Long id, String formId, String working, String status, String cCategory,
            String cClass, String cComponent, String systemId, String system, String userId, String cuserId,
            String astatus, String sstatus, Date ect, Date onLineTime, Date offLineTime, String isReset,
            String isProduction, String isTest, String isHandleFirst, String isForward, String isInterrupt,
            String summary, String purpose, String content, String effectScope, String remark, String reset,
            String countersigneds, String updatedBy, Date updatedAt, String createdBy, Date createdAt, String spcGroups) {
        this.id = id;
        this.formId = formId;
        this.working = working;
        this.status = status;
        this.cCategory = cCategory;
        this.cClass = cClass;
        this.cComponent = cComponent;
        this.systemId = systemId;
        this.system = system;
        this.userId = userId;
        this.cuserId = cuserId;
        this.astatus = astatus;
        this.ect = ect;
        this.onLineTime = onLineTime;
        this.offLineTime = offLineTime;
        this.isReset = isReset;
        this.isProduction = isProduction;
        this.isTest = isTest;
        this.isHandleFirst = isHandleFirst;
        this.isForward = isForward;
        this.isInterrupt = isInterrupt;
        this.summary = summary;
        this.purpose = purpose;
        this.content = content;
        this.effectScope = effectScope;
        this.remark = remark;
        this.reset = reset;
        this.countersigneds = countersigneds;
        this.spcGroups = spcGroups;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "Id", unique = true, nullable = false)
    public Long getId () {
        return this.id;
    }

    public void setId (Long id) {
        this.id = id;
    }

    @Column(name = "FormId", unique = true, nullable = false)
    public String getFormId () {
        return this.formId;
    }

    public void setFormId (String formId) {
        this.formId = formId;
    }

    @Column(name = "Working")
    public String getWorking () {
        return this.working;
    }

    public void setWorking (String working) {
        this.working = working;
    }

    @Column(name = "Status")
    public String getStatus () {
        return this.status;
    }

    public void setStatus (String status) {
        this.status = status;
    }

    @Column(name = "CCategory")
    public String getcCategory () {
        return this.cCategory;
    }

    public void setcCategory (String cCategory) {
        this.cCategory = cCategory;
    }

    @Column(name = "CClass")
    public String getcClass () {
        return this.cClass;
    }

    public void setcClass (String cClass) {
        this.cClass = cClass;
    }

    @Column(name = "CComponent")
    public String getcComponent () {
        return this.cComponent;
    }

    public void setcComponent (String cComponent) {
        this.cComponent = cComponent;
    }

    @Column(name = "SystemId")
    public String getSystemId () {
        return this.systemId;
    }

    public void setSystemId (String systemId) {
        this.systemId = systemId;
    }

    @Column(name = "System")
    public String getSystem () {
        return this.system;
    }

    public void setSystem (String system) {
        this.system = system;
    }

    @Column(name = "UserId")
    public String getUserId () {
        return this.userId;
    }

    public void setUserId (String userId) {
        this.userId = userId;
    }

    @Column(name = "CUserId")
    public String getCuserId () {
        return this.cuserId;
    }

    public void setCuserId (String cuserId) {
        this.cuserId = cuserId;
    }

    @Column(name = "AStatus")
    public String getAstatus () {
        return this.astatus;
    }

    public void setAstatus (String astatus) {
        this.astatus = astatus;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "ECT", length = 23)
    public Date getEct () {
        return this.ect;
    }

    public void setEct (Date ect) {
        this.ect = ect;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "OnLineTime", length = 23)
    public Date getOnLineTime () {
        return this.onLineTime;
    }

    public void setOnLineTime (Date onLineTime) {
        this.onLineTime = onLineTime;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "OffLineTime", length = 23)
    public Date getOffLineTime () {
        return this.offLineTime;
    }

    public void setOffLineTime (Date offLineTime) {
        this.offLineTime = offLineTime;
    }

    @Column(name = "IsReset", length = 1)
    public String getIsReset () {
        return this.isReset;
    }

    public void setIsReset (String isReset) {
        this.isReset = isReset;
    }

    @Column(name = "IsProduction", length = 1)
    public String getIsProduction () {
        return this.isProduction;
    }

    public void setIsProduction (String isProduction) {
        this.isProduction = isProduction;
    }

    @Column(name = "IsTest", length = 1)
    public String getIsTest () {
        return this.isTest;
    }

    public void setIsTest (String isTest) {
        this.isTest = isTest;
    }

    @Column(name = "IsHandleFirst", length = 1)
    public String getIsHandleFirst () {
        return this.isHandleFirst;
    }

    public void setIsHandleFirst (String isHandleFirst) {
        this.isHandleFirst = isHandleFirst;
    }

    @Column(name = "IsForward", length = 1)
    public String getIsForward () {
        return this.isForward;
    }

    public void setIsForward (String isForward) {
        this.isForward = isForward;
    }

    @Column(name = "IsInterrupt", length = 1)
    public String getIsInterrupt () {
        return this.isInterrupt;
    }

    public void setIsInterrupt (String isInterrupt) {
        this.isInterrupt = isInterrupt;
    }

    @Column(name = "Summary")
    public String getSummary () {
        return this.summary;
    }

    public void setSummary (String summary) {
        this.summary = summary;
    }

    @Column(name = "Purpose")
    public String getPurpose () {
        return this.purpose;
    }

    public void setPurpose (String purpose) {
        this.purpose = purpose;
    }

    @Column(name = "Content")
    public String getContent () {
        return this.content;
    }

    public void setContent (String content) {
        this.content = content;
    }

    @Column(name = "EffectScope")
    public String getEffectScope () {
        return this.effectScope;
    }

    public void setEffectScope (String effectScope) {
        this.effectScope = effectScope;
    }

    @Column(name = "Remark")
    public String getRemark () {
        return this.remark;
    }

    public void setRemark (String remark) {
        this.remark = remark;
    }

    @Column(name = "Reset")
    public String getReset () {
        return this.reset;
    }

    public void setReset (String reset) {
        this.reset = reset;
    }

    @Column(name = "Countersigneds")
    public String getCountersigneds () {
        return this.countersigneds;
    }

    public void setCountersigneds (String countersigneds) {
        this.countersigneds = countersigneds;
    }

    @Column(name = "SpcGroups")
    public String getSpcGroups () {
        return spcGroups;
    }

    public void setSpcGroups (String spcGroups) {
        this.spcGroups = spcGroups;
    }

}
