package com.ebizprise.winw.project.entity;
// Generated 2019/8/30 下午 01:55:06 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

import com.ebizprise.winw.project.base.entity.BaseEntity;

/**
 * FormFile generated by hbm2java
 */
@Entity
@Table(name = "FORM_FILE_LOG")
public class FormFileLogEntity extends BaseEntity {

    private Long id;
    private String formId;
    private String actionType;
    
    public FormFileLogEntity() {
    }

    public FormFileLogEntity(Long id) {
        this.id = id;
    }
    
    public FormFileLogEntity(Long id, String formId, String actionType) {
        this.id = id;
        this.formId = formId;
        this.actionType = actionType;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "Id", unique = true, nullable = false)
    public Long getId () {
        return this.id;
    }

    public void setId (Long id) {
        this.id = id;
    }

    @Column(name = "FormId", length = 20)
    public String getFormId () {
        return this.formId;
    }

    public void setFormId (String formId) {
        this.formId = formId;
    }

    @Column(name = "ActionType")
    public String getActionType () {
        return actionType;
    }

    public void setActionType (String actionType) {
        this.actionType = actionType;
    }

}
