package com.ebizprise.winw.project.entity;
// Generated 2019/8/30 下午 02:45:36 by Hibernate Tools 4.0.0

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.ebizprise.winw.project.base.entity.BaseEntity;

/**
 * FormJobLibrary generated by hbm2java
 */
@Entity
@Table(name = "FORM_JOB_LIBRARY")
public class FormJobLibraryEntity extends BaseEntity {

    private Long id;
    private String formId;
    private String result;
    private Date time;
    private String content;
    private String rowType;
    private String qyStatus;

    public FormJobLibraryEntity() {
    }

    public FormJobLibraryEntity(Long id, String formId) {
        this.id = id;
        this.formId = formId;
    }

    public FormJobLibraryEntity(Long id, String formId, String result, Date time, String content,
            String updatedBy, Date updatedAt, String createdBy, Date createdAt, String rowType, String qyStatus) {
        this.id = id;
        this.formId = formId;
        this.result = result;
        this.time = time;
        this.content = content;
        this.rowType = rowType;
        this.qyStatus = qyStatus;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "Id", unique = true, nullable = false)
    public Long getId () {
        return this.id;
    }

    public void setId (Long id) {
        this.id = id;
    }

    @Column(name = "FormId", unique = true, nullable = false)
    public String getFormId () {
        return this.formId;
    }

    public void setFormId (String formId) {
        this.formId = formId;
    }

    @Column(name = "Result")
    public String getResult () {
        return this.result;
    }

    public void setResult (String result) {
        this.result = result;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "Time", length = 23)
    public Date getTime () {
        return this.time;
    }

    public void setTime (Date time) {
        this.time = time;
    }

    @Column(name = "Content")
    public String getContent () {
        return this.content;
    }

    public void setContent (String content) {
        this.content = content;
    }

    @Column(name = "RowType")
    public String getRowType () {
        return rowType;
    }

    public void setRowType (String rowType) {
        this.rowType = rowType;
    }

    @Column(name = "QyStatus")
    public String getQyStatus () {
        return qyStatus;
    }

    public void setQyStatus (String qyStatus) {
        this.qyStatus = qyStatus;
    }

}
