package com.ebizprise.winw.project.entity;
// Generated 2019/12/8 下午 05:01:04 by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.ebizprise.winw.project.base.entity.BaseEntity;

/**
 * FormJobLibraryFile generated by hbm2java
 */
@Entity
@Table(name = "FORM_JOB_LIBRARY_FILE")
public class FormJobLibraryFileEntity extends BaseEntity {

    private Long id;
    private String formId;
    private String name;
    private Date time;
    private byte[] data;

    public FormJobLibraryFileEntity() {
    }

    public FormJobLibraryFileEntity(Long id) {
        this.id = id;
    }

    public FormJobLibraryFileEntity(Long id, String formId, String name, Date time, byte[] data, String updatedBy,
            Date updatedAt, String createdBy, Date createdAt) {
        this.id = id;
        this.formId = formId;
        this.name = name;
        this.time = time;
        this.data = data;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "Id", unique = true, nullable = false)
    public Long getId () {
        return this.id;
    }

    public void setId (Long id) {
        this.id = id;
    }

    @Column(name = "FormId", length = 20)
    public String getFormId () {
        return this.formId;
    }

    public void setFormId (String formId) {
        this.formId = formId;
    }

    @Column(name = "Name")
    public String getName () {
        return this.name;
    }

    public void setName (String name) {
        this.name = name;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "Time", length = 23)
    public Date getTime () {
        return this.time;
    }

    public void setTime (Date time) {
        this.time = time;
    }

    @Column(name = "Data")
    public byte[] getData () {
        return this.data;
    }

    public void setData (byte[] data) {
        this.data = data;
    }

}
