package com.ebizprise.winw.project.entity;
// Generated 2019/8/30 下午 02:45:36 by Hibernate Tools 4.0.0

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

import com.ebizprise.winw.project.base.entity.BaseEntity;

/**
 * FormJobInfoWorkingItems generated by hbm2java
 */
@Entity
@Table(name = "FORM_JOB_INFO_WORKING_ITEMS")
public class FormJobInfoWorkingItemsEntity extends BaseEntity {

    private Long id;
    private String formId;
    private String item;
    private String isImpact;
    private String isReview;

    public FormJobInfoWorkingItemsEntity() {
    }

    public FormJobInfoWorkingItemsEntity(Long id, String formId) {
        this.id = id;
        this.formId = formId;
    }

    public FormJobInfoWorkingItemsEntity(Long id, String formId, String item, String isImpact,
            String isReview, String updatedBy, Date updatedAt, String createdBy, Date createdAt) {
        this.id = id;
        this.formId = formId;
        this.item = item;
        this.isImpact = isImpact;
        this.isReview = isReview;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "Id", unique = true, nullable = false)
    public Long getId () {
        return this.id;
    }

    public void setId (Long id) {
        this.id = id;
    }

    @Column(name = "FormId", nullable = false)
    public String getFormId () {
        return this.formId;
    }

    public void setFormId (String formId) {
        this.formId = formId;
    }

    @Column(name = "Item")
    public String getItem () {
        return this.item;
    }

    public void setItem (String item) {
        this.item = item;
    }

    @Column(name = "IsImpact", length = 1)
    public String getIsImpact () {
        return this.isImpact;
    }

    public void setIsImpact (String isImpact) {
        this.isImpact = isImpact;
    }

    @Column(name = "IsReview", length = 1)
    public String getIsReview () {
        return this.isReview;
    }

    public void setIsReview (String isReview) {
        this.isReview = isReview;
    }

}
