package com.ebizprise.winw.project.entity;
// Generated 2019/8/20 下午 04:17:17 by Hibernate Tools 4.0.0

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

import com.ebizprise.winw.project.base.entity.BaseEntity;

/**
 * FormFields generated by hbm2java
 */
@Entity
@Table(name = "FORM_FIELDS")
public class FormFieldsEntity extends BaseEntity {

    private Long id;
    private String formClass;
    private String formFields;

    public FormFieldsEntity() {
    }

    public FormFieldsEntity(Long id, String formClass, String formFields) {
        this.id = id;
        this.formClass = formClass;
        this.formFields = formFields;
    }

    public FormFieldsEntity(Long id, String formClass, String formFields, String updatedBy, Date updatedAt,
            String createdBy, Date createdAt) {
        this.id = id;
        this.formClass = formClass;
        this.formFields = formFields;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "Id", unique = true, nullable = false)
    public Long getId () {
        return this.id;
    }

    public void setId (Long id) {
        this.id = id;
    }

    @Column(name = "FormClass", unique = true, nullable = false)
    public String getFormClass () {
        return this.formClass;
    }

    public void setFormClass (String formClass) {
        this.formClass = formClass;
    }

    @Column(name = "FormFields", nullable = false)
    public String getFormFields () {
        return this.formFields;
    }

    public void setFormFields (String formFields) {
        this.formFields = formFields;
    }

}
