package com.ebizprise.winw.project.entity;
// Generated 2019/8/30 下午 02:45:36 by Hibernate Tools 4.0.0

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

import com.ebizprise.winw.project.base.entity.BaseEntity;

/**
 * FormJobInfoApDetail generated by hbm2java
 */
@Entity
@Table(name = "FORM_JOB_INFO_AP_DETAIL")
public class FormJobInfoApDetailEntity extends BaseEntity {

    private Long id;
    private String formId;
    private String sClass;
    private String sSubClass;
    private String changeType;
    private String changeRank;
    private String systemId;
    private String system;
    private String isHandleFirst;
    private String isCorrect;
    private String isAddFuntion;
    private String isForward;
    private String isWatching;
    private String isAddReport;
    private String isAddFile;
    private String isProgramOnline;
    private String isModifyProgram;
    private String purpose;
    private String content;
    private String countersigneds;

    public FormJobInfoApDetailEntity() {
    }

    public FormJobInfoApDetailEntity(Long id, String formId) {
        this.id = id;
        this.formId = formId;
    }

    public FormJobInfoApDetailEntity(Long id, String formId, String sClass, String sSubClass,
            String changeType, String changeRank, String systemId,String system, String isHandleFirst, String isCorrect,
            String isAddFuntion, String isForward, String isWatching, String isAddReport, String isAddFile,
            String isModifyProgram, String purpose, String content, String countersigneds, 
            String updatedBy, Date updatedAt, String createdBy, Date createdAt) {
        this.id = id;
        this.formId = formId;
        this.sClass = sClass;
        this.sSubClass = sSubClass;
        this.changeType = changeType;
        this.changeRank = changeRank;
        this.systemId = systemId;
        this.system = system;
        this.isHandleFirst = isHandleFirst;
        this.isCorrect = isCorrect;
        this.isAddFuntion = isAddFuntion;
        this.isForward = isForward;
        this.isWatching = isWatching;
        this.isAddReport = isAddReport;
        this.isAddFile = isAddFile;
        this.isModifyProgram = isModifyProgram;
        this.purpose = purpose;
        this.content = content;
        this.countersigneds = countersigneds;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "Id", unique = true, nullable = false)
    public Long getId () {
        return this.id;
    }

    public void setId (Long id) {
        this.id = id;
    }

    @Column(name = "FormId", unique = true, nullable = false)
    public String getFormId () {
        return this.formId;
    }

    public void setFormId (String formId) {
        this.formId = formId;
    }

    @Column(name = "SClass")
    public String getSclass () {
        return this.sClass;
    }

    public void setSclass (String sClass) {
        this.sClass = sClass;
    }

    @Column(name = "SSubClass")
    public String getSsubClass () {
        return this.sSubClass;
    }

    public void setSsubClass (String sSubClass) {
        this.sSubClass = sSubClass;
    }

    @Column(name = "ChangeType")
    public String getChangeType () {
        return this.changeType;
    }

    public void setChangeType (String changeType) {
        this.changeType = changeType;
    }

    @Column(name = "ChangeRank")
    public String getChangeRank () {
        return this.changeRank;
    }

    public void setChangeRank (String changeRank) {
        this.changeRank = changeRank;
    }

    @Column(name = "System")
    public String getSystem () {
        return this.system;
    }

    public void setSystem (String system) {
        this.system = system;
    }

    @Column(name = "IsHandleFirst", length = 1)
    public String getIsHandleFirst () {
        return this.isHandleFirst;
    }

    public void setIsHandleFirst (String isHandleFirst) {
        this.isHandleFirst = isHandleFirst;
    }

    @Column(name = "IsCorrect", length = 1)
    public String getIsCorrect () {
        return this.isCorrect;
    }

    public void setIsCorrect (String isCorrect) {
        this.isCorrect = isCorrect;
    }

    @Column(name = "IsAddFuntion", length = 1)
    public String getIsAddFuntion () {
        return this.isAddFuntion;
    }

    public void setIsAddFuntion (String isAddFuntion) {
        this.isAddFuntion = isAddFuntion;
    }

    @Column(name = "IsForward", length = 1)
    public String getIsForward () {
        return this.isForward;
    }

    public void setIsForward (String isForward) {
        this.isForward = isForward;
    }

    @Column(name = "IsWatching", length = 1)
    public String getIsWatching () {
        return this.isWatching;
    }

    public void setIsWatching (String isWatching) {
        this.isWatching = isWatching;
    }

    @Column(name = "IsAddReport", length = 1)
    public String getIsAddReport () {
        return this.isAddReport;
    }

    public void setIsAddReport (String isAddReport) {
        this.isAddReport = isAddReport;
    }

    @Column(name = "IsAddFile", length = 1)
    public String getIsAddFile () {
        return this.isAddFile;
    }

    public void setIsAddFile (String isAddFile) {
        this.isAddFile = isAddFile;
    }

    @Column(name = "Purpose")
    public String getPurpose () {
        return this.purpose;
    }

    public void setPurpose (String purpose) {
        this.purpose = purpose;
    }

    @Column(name = "Content")
    public String getContent () {
        return this.content;
    }

    public void setContent (String content) {
        this.content = content;
    }

    @Column(name = "Countersigneds")
    public String getCountersigneds () {
        return this.countersigneds;
    }

    public void setCountersigneds (String countersigneds) {
        this.countersigneds = countersigneds;
    }

    @Column(name = "SystemId")
    public String getSystemId() {
        return systemId;
    }

    public void setSystemId(String systemId) {
        this.systemId = systemId;
    }

    @Column(name = "IsProgramOnline", length = 1)
    public String getIsProgramOnline () {
        return isProgramOnline;
    }

    public void setIsProgramOnline (String isProgramOnline) {
        this.isProgramOnline = isProgramOnline;
    }

    @Column(name = "IsModifyProgram", length = 1)
    public String getIsModifyProgram () {
        return isModifyProgram;
    }

    public void setIsModifyProgram (String isModifyProgram) {
        this.isModifyProgram = isModifyProgram;
    }

}
