package com.ebizprise.winw.project.entity;
// Generated 2020/6/23 下午 02:50:05 by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.ebizprise.winw.project.base.entity.BaseEntity;

/**
 * SysHoliday generated by hbm2java
 */
@Entity
@Table(name = "SYS_HOLIDAY")
public class SysHolidayEntity extends BaseEntity {

    private Long id;
    private String year;
    private Date date;
    private String name;
    private String isHoliday;
    private String holidayCategory;
    private String description;
    private String fileName;

    public SysHolidayEntity() {
    }

    public SysHolidayEntity(Long id, String year) {
        this.id = id;
        this.year = year;
    }

    public SysHolidayEntity(Long id, String updatedBy, Date updatedAt, String createdBy, Date createdAt,
            String year, Date date, String name, String isHoliday, String holidayCategory,
            String description, String fileName) {
        this.id = id;
        this.year = year;
        this.date = date;
        this.name = name;
        this.isHoliday = isHoliday;
        this.holidayCategory = holidayCategory;
        this.description = description;
        this.fileName = fileName;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "Id", unique = true, nullable = false)
    public Long getId () {
        return this.id;
    }

    public void setId (Long id) {
        this.id = id;
    }

    @Column(name = "Year", nullable = false)
    public String getYear () {
        return this.year;
    }

    public void setYear (String year) {
        this.year = year;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "Date", length = 23)
    public Date getDate () {
        return this.date;
    }

    public void setDate (Date date) {
        this.date = date;
    }

    @Column(name = "Name")
    public String getName () {
        return this.name;
    }

    public void setName (String name) {
        this.name = name;
    }

    @Column(name = "IsHoliday", length = 1)
    public String getIsHoliday () {
        return this.isHoliday;
    }

    public void setIsHoliday (String isHoliday) {
        this.isHoliday = isHoliday;
    }

    @Column(name = "HolidayCategory")
    public String getHolidayCategory () {
        return this.holidayCategory;
    }

    public void setHolidayCategory (String holidayCategory) {
        this.holidayCategory = holidayCategory;
    }

    @Column(name = "Description")
    public String getDescription () {
        return this.description;
    }

    public void setDescription (String description) {
        this.description = description;
    }

    @Column(name = "FileName")
    public String getFileName () {
        return fileName;
    }

    public void setFileName (String fileName) {
        this.fileName = fileName;
    }

}
