package com.ebizprise.winw.project.entity;
// Generated 2020/6/16 下午 04:12:45 by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import com.ebizprise.winw.project.base.entity.BaseEntity;

/**
 * SysMailLog generated by hbm2java
 */
@Entity
@Table(name = "SYS_MAIL_LOG")
public class SysMailLogEntity extends BaseEntity {

    private Long id;
    private String recognize;
    private String addresses;

    public SysMailLogEntity() {
    }

    public SysMailLogEntity(Long id, String recognize) {
        this.id = id;
        this.recognize = recognize;
    }

    public SysMailLogEntity(Long id, String recognize, String addresses, String updatedBy, Date updatedAt,
            String createdBy, Date createdAt) {
        this.id = id;
        this.recognize = recognize;
        this.addresses = addresses;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "Id", unique = true, nullable = false)
    public Long getId () {
        return this.id;
    }

    public void setId (Long id) {
        this.id = id;
    }

    @Column(name = "Recognize", nullable = false)
    public String getRecognize () {
        return this.recognize;
    }

    public void setRecognize (String recognize) {
        this.recognize = recognize;
    }

    @Column(name = "Addresses")
    public String getAddresses () {
        return this.addresses;
    }

    public void setAddresses (String addresses) {
        this.addresses = addresses;
    }

}
