package com.ebizprise.winw.project.entity;
// Generated 2019/7/16 下午 04:10:57 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import com.ebizprise.winw.project.base.entity.BaseEntity;

/**
 * System generated by hbm2java
 */
@Entity
@Table(name = "SYSTEM", uniqueConstraints = {@UniqueConstraint(columnNames = {"systemBrand"})})
public class SystemEntity extends BaseEntity {

    private Long id; //流水號
    private String systemBrand; //系統名稱識別碼，唯一值
    private String systemId; //系統編號(系統名稱_代碼)
    private String systemName; //系統名稱(系統中文說明)
    private String description; //系統描述
    private String department; //部門代號
    private String mboName;
    private String mark; //資訊資產群組
    private Integer opinc;
    private Integer apinc;
    private String active; //狀態 _是否啟用
    private String limit; //極限值

    public SystemEntity() {
    }

    public SystemEntity(Long id, String systemBrand, String systemId, String active) {
        this.id = id;
        this.systemBrand = systemBrand;
        this.systemId = systemId;
        this.active = active;
    }

    public SystemEntity(Long id, String systemBrand, String systemId, String systemName, String description,
            String department, String mboName, String mark, Integer opinc, Integer apinc, String active, String limit) {
        this.id = id;
        this.systemBrand = systemBrand;
        this.systemId = systemId;
        this.systemName = systemName;
        this.description = description;
        this.department = department;
        this.mboName = mboName;
        this.mark = mark;
        this.opinc = opinc;
        this.apinc = apinc;
        this.active = active;
        this.limit = limit;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "Id", unique = true, nullable = false)
    public Long getId () {
        return this.id;
    }

    public void setId (Long id) {
        this.id = id;
    }

    @Column(name = "SystemBrand", unique = true, nullable = false)
    public String getSystemBrand () {
        return this.systemBrand;
    }

    public void setSystemBrand (String systemBrand) {
        this.systemBrand = systemBrand;
    }

    @Column(name = "SystemId", unique = true, nullable = false)
    public String getSystemId () {
        return this.systemId;
    }

    public void setSystemId (String systemId) {
        this.systemId = systemId;
    }

    @Column(name = "SystemName")
    public String getSystemName () {
        return this.systemName;
    }

    public void setSystemName (String systemName) {
        this.systemName = systemName;
    }

    @Column(name = "Description")
    public String getDescription () {
        return this.description;
    }

    public void setDescription (String description) {
        this.description = description;
    }

    @Column(name = "Department")
    public String getDepartment () {
        return this.department;
    }

    public void setDepartment (String department) {
        this.department = department;
    }

    @Column(name = "MboName")
    public String getMboName () {
        return this.mboName;
    }

    public void setMboName (String mboName) {
        this.mboName = mboName;
    }

    @Column(name = "Mark")
    public String getMark () {
        return this.mark;
    }

    public void setMark (String mark) {
        this.mark = mark;
    }

    @Column(name = "Opinc")
    public Integer getOpinc () {
        return this.opinc;
    }

    public void setOpinc (Integer opinc) {
        this.opinc = opinc;
    }

    @Column(name = "Apinc")
    public Integer getApinc () {
        return this.apinc;
    }

    public void setApinc (Integer apinc) {
        this.apinc = apinc;
    }

    @Column(name = "Active", nullable = false)
    public String getActive () {
        return this.active;
    }

    public void setActive (String active) {
        this.active = active;
    }

    @Column(name = "Limit", nullable = false)
    public String getLimit () {
        return limit;
    }

    public void setLimit (String limit) {
        this.limit = limit;
    }

}
