SELECT
    F.FORMID         AS 'FORMID',
    F.CREATETIME     AS 'CREATETIME',
    FJID.SIT         AS 'SIT',
    F.USERSOLVING    AS 'USERSOLVING',
    F.FORMSTATUS     AS 'STATUS',
    FJIAD.PURPOSE    AS 'PORPOSE',
    FJID.ISPLANING   AS 'PLANING',
    FJID.ISUNPLANING AS 'UNPLANING',
    FJID.IST         AS 'IST',
    FJID.ICT         AS 'ICT',
    SO1.DISPLAY      AS 'SO1',
    SO1.DISPLAY      AS 'SO2',
    FJIAD.SYSTEM     AS 'SYSTEM'
FROM
    FORM F
JOIN
    FORM_JOB_INFO_DATE FJID
ON
    F.FORMID = FJID.FORMID
JOIN
    FORM_JOB_INFO_AP_DETAIL FJIAD
ON
    F.FORMID = FJIAD.FORMID
JOIN
    SYS_OPTION SO1
ON
    SO1.VALUE = FJIAD.SCLASS
JOIN
    SYS_OPTION SO2
ON
    SO2.VALUE = FJIAD.SSUBCLASS
WHERE
    F.FORMCLASS = 'JOB_AP'
AND F.FORMSTATUS = 'CLOSED'
AND FJID.IST BETWEEN :startDate AND :endDate
AND  NOT EXISTS ( SELECT 1 FROM _f WHERE f.FormId = FormId AND division = 'A01421' ) 
${CONDITIONS}
ORDER BY
    F.CREATETIME