DELETE FROM FORM WHERE FormId = :formId

DELETE FROM FORM_CONTENT_MODIFY_LOG WHERE FormId = :formId

DELETE FROM FORM_FILE WHERE FormId = :formId

DELETE FROM FORM_IMPACT_ANALYSIS WHERE FormId = :formId

DELETE FROM FORM_INFO_C_DETAIL WHERE FormId = :formId

DELETE FROM FORM_INFO_CHG_DETAIL WHERE FormId = :formId

DELETE FROM FORM_INFO_DATE WHERE FormId = :formId

DELETE FROM FORM_INFO_INC_DETAIL WHERE FormId = :formId

DELETE FROM FORM_INFO_Q_DETAIL WHERE FormId = :formId

DELETE FROM FORM_INFO_SR_DETAIL WHERE FormId = :formId

DELETE FROM FORM_INFO_USER WHERE FormId = :formId

DELETE FROM FORM_JOB_BATCH WHERE FormId = :formId

DELETE FROM FORM_JOB_CHECK_PERSON_LIST WHERE FormId = :formId

DELETE FROM FORM_JOB_COUNTERSIGNED WHERE FormId = :formId

DELETE FROM FORM_JOB_INFO_AP_DETAIL WHERE FormId = :formId

DELETE FROM FORM_JOB_INFO_DATE WHERE FormId = :formId

DELETE FROM FORM_JOB_INFO_SYS_DETAIL WHERE FormId = :formId

DELETE FROM FORM_JOB_INFO_WORKING_ITEMS WHERE FormId = :formId

DELETE FROM FORM_JOB_LIBRARY WHERE FormId = :formId

DELETE FROM FORM_JOB_WORKING WHERE FormId = :formId

DELETE FROM FORM_PROGRAM WHERE FormId = :formId

DELETE FROM FORM_USER_RECORD WHERE FormId = :formId

DELETE FROM FORM_VERIFY_LOG WHERE FormId = :formId