SELECT SUMMARY FROM FORM_INFO_SR_DETAIL WHERE FORMID = :formId
UNION
SELECT SUMMARY FROM FORM_INFO_Q_DETAIL WHERE FORMID = :formId
UNION
SELECT SUMMARY FROM FORM_INFO_INC_DETAIL WHERE FORMID = :formId