WITH CTE_REVERSE AS (
SELECT Id, FormId, SourceId, FormClass FROM FORM WHERE FormId = :formId
UNION ALL
SELECT F.Id, F.FormId, F.SourceId, F.FormClass FROM FORM F JOIN CTE_REVERSE ON F.FormId = CTE_REVERSE.SourceId
)
SELECT * FROM CTE_REVERSE ORDER BY Id;