  SELECT GROUPID FROM FORM_PROCESS_DETAIL_REVIEW_SR
  WHERE DETAILID = :detailId and PROCESSORDER = :processOrder
  UNION
  SELECT GROUPID FROM FORM_PROCESS_DETAIL_REVIEW_Q
  WHERE DETAILID = :detailId and PROCESSORDER = :processOrder
  UNION
  SELECT GROUPID FROM FORM_PROCESS_DETAIL_REVIEW_INC
  WHERE DETAILID = :detailId and PROCESSORDER = :processOrder