  SELECT GROUPID FROM FORM_PROCESS_DETAIL_APPLY_SR
  WHERE DETAILID = :detailId and PROCESSORDER = :processOrder
  UNION
  SELECT GROUPID FROM FORM_PROCESS_DETAIL_APPLY_Q
  WHERE DETAILID = :detailId and PROCESSORDER = :processOrder
  UNION
  SELECT GROUPID FROM FORM_PROCESS_DETAIL_APPLY_INC
  WHERE DETAILID = :detailId and PROCESSORDER = :processOrder