package com.ebizprise.winw.project.enums.form.editable;

/**
 * 紀錄申請/審核階段的可編輯欄位<br><br>
 * 
 * 欄位名稱與HTML的欄位屬性name對應<br>
 * 參考文件 : WINW003_表單作業_可修改欄位一覽表(具可修改欄位權限者)
 * 
 * @author adam.yeh
 */
public enum EditableEnum implements BaseColEnum {

    Q(
        UNIT_ID,
        USER_NAME,
        UNIT_CATEGORY,
        PHONE,
        EMAIL,
        SCLASS,
        SSUBCLASS,
        SYSTEM,
        SYSTEM_ID,
        ASSET_GROUP,
        SYSTEM_BRAND,
        QUESTION_ID,
        SUMMARY,
        CONTENT,
        IS_SPECIAL,
        ECT,
        AST,
        ACT,
        OBSERVATION,
        TEMPORARY,
        KNOWLEDGE_1,
        KNOWLEDGE_2,
        KNOWLEDGE_DIALOG
    ),
    SR(
        UNIT_ID,
        USER_NAME,
        UNIT_CATEGORY,
        PHONE,
        EMAIL,
        SCLASS,
        SSUBCLASS,
        SYSTEM,
        SYSTEM_ID,
        ASSET_GROUP,
        SYSTEM_BRAND,
        SYSTEM_DIALOG,
        ASSET_GROUP,
        CLIST,
        SUMMARY,
        CONTENT,
        DIVISION,
        DIVISION_WORDING,
        EOT,
        ECT,
        ACT
    ),
    INC(
        UNIT_ID,
        USER_NAME,
        UNIT_CATEGORY,
        PHONE,
        EMAIL,
        SCLASS,
        SSUBCLASS,
        SYSTEM,
        SYSTEM_ID,
        ASSET_GROUP,
        SYSTEM_BRAND,
        CLIST,
        SUMMARY,
        CONTENT,
        EVENT_CLASS,
        EVENT_TYPE,
        EVENT_SECURITY,
        INCFORM_DAILOG,
        IS_IVR,
        IS_INTERRUPT,
        IS_MAINEVENT,
        ACT,
        ASSIGN_TIME,
        EXCLUDE_TIME
    ),
    CHG(
        CCT,
        CCLASS,
        CCATEGORY,
        CCOMPONENT_DIALOG,
        SUMMARY,
        CONTENT,
        EFFECT_SYSTEM,
        IS_URGENT,
        IS_EFFECTFIELD,
        IS_EFFECTACCOUNTANT,
        SOLUTION,
        EVALUATION
    ),
    Q_C(
        EOT,
        ECT,
        AST,
        ACT,
        COUNTERSIGNED_HANDLE
    ),
    SR_C(
        COUNTERSIGNED_HANDLE
    ),
    INC_C(
        AST,
        ACT,
        COUNTERSIGNED_HANDLE
    ),
    JOB_AP(
        BOOK,
        ONLY,
        LINK,
        OTHER,
        LINK_ONLY,
        ONLY_CODE,
        LINK_CODE,
        BOOK_NUMBER,
        LINK_NUMBER,
        ONLY_NUMBER,
        LINKONLY_NUMBER,
        CLIST,
        PURPOSE,
        CONTENT,
        DESCRIPTION,
        ROLLBACK_DESC,
        IS_ADDFILE,
        IS_PROGRAM_ONLINE,
        IS_CORRECT,
        IS_PLANING,
        IS_ROLLBACK,
        IS_UNPLANING,
        IS_ADDREPORT,
        IS_ADDFUNTION,
        IS_HANDLEFIRST,
        IST,
        ICT,
        TCT,
        SCT,
        SIT,
        OFFLINE_TIME,
        SCLASS,
        SYSTEM,
        SYSTEM_ID,
        SYSTEM_BRAND,
        SYSTEM_DIALOG,
        IS_MODIFYPROGRAM
    ),
    JOB_SP(
        RESET,
        CLIST,
        REMARK,
        SUMMARY,
        CONTENT,
        WORKING,
        EFFECT_SCOPE_2,
        IS_RESET,
        IS_FORWARD,
        IS_INTERRUPT,
        IS_HANDLEFIRST,
        AST,
        ACT,
        EOT,
        MECT,
        ONLINE_TIME,
        OFFLINE_TIME,
        WORK_ITEM,
        IS_TEST,
        IS_PRODUCTION,
        IS_MODIFYPROGRAM
    ),
    JOB_AP_C(
        CLIST,
        PURPOSE,
        CONTENT,
        DESCRIPTION,
        ROLLBACK_DESC,
        IS_ADDFILE,
        IS_PROGRAM_ONLINE,
        IS_FORWARD,
        IS_CORRECT,
        IS_PLANING,
        IS_ROLLBACK,
        IS_ADDREPORT,
        IS_UNPLANING,
        IS_ADDFUNTION,
        IS_HANDLEFIRST,
        TCT,
        IST,
        SCT,
        ICT,
        SIT,
        OFFLINE_TIME,
        BOOK,
        ONLY,
        LINK,
        OTHER,
        LINK_ONLY,
        ONLY_CODE,
        LINK_CODE,
        BOOK_NUMBER,
        LINK_NUMBER,
        ONLY_NUMBER,
        LINKONLY_NUMBER
    ),
    JOB_SP_C(
        IS_TEST,
        IS_PRODUCTION,
        IS_HANDLEFIRST,
        REMARK,
        SUMMARY,
        PURPOSE,
        CONTENT,
        COUNTERSIGNEDS,
        EOT,
        ECT,
        ACT,
        AST,
        MECT
    ),
    BA(
        EXECUTE_TIME_WORDING,
        DB_IN_USE_WORDING,
        DIVISION
    ),
    KL();

    private String[] columns;

    private EditableEnum (String... columns) {
        this.columns = columns;
    }
    
    public String[] columns () {
        return this.columns;
    }
    
}
