package com.ebizprise.winw.project.enums.form.editable;

/**
 * 紀錄申請第一關的可編輯欄位<br><br>
 * 
 * 欄位名稱與HTML的欄位屬性name對應<br>
 * 參考文件 : WINW003_表單作業_可修改欄位一覽表(具可修改欄位權限者)
 * 
 * @author adam.yeh
 */
public enum EditOneEnum implements BaseColEnum {

    Q(
        QUESTION_ID,
        UNIT_CATEGORY,
        UNIT_ID,
        USER_NAME,
        PHONE,
        EMAIL,
        SUMMARY,
        CONTENT,
        CCLASS,
        CCATEGORY,
        CCOMPONENT,
        CCOMPONENT_DIALOG,
        CLIST,
        SCLASS,
        SSUBCLASS,
        SYSTEM,
        SYSTEM_ID,
        SYSTEM_BRAND,
        SYSTEM_DIALOG,
        ASSET_GROUP,
        EFFECT_SCOPE,
        EFFECT_SCOPE_BTN,
        EFFECT_SCOPE_WORDING,
        URGENT_LEVEL,
        URGENT_LEVEL_BTN,
        URGENT_LEVEL_WORDING,
        QUESTIONP_RIORITY,
        QUESTION_PRIORITY_WORDING,
        REPORT_TIME,
        AST,
        IS_SPECIAL,
        SPECIAL_ENDCASETYPE,
        ECT,
        OBSERVATION,
        IS_SUGGESTCASE,
        INDICATION,
        REASON,
        PROCESS_PROGRAM,
        TEMPORARY,
        KNOWLEDGE_1,
        KNOWLEDGE_2,
        KNOWLEDGE_DIALOG
    ),
    SR(
        UNIT_ID,
        USER_NAME,
        UNIT_CATEGORY,
        PHONE,
        EMAIL,
        SUMMARY,
        CONTENT,
        CCLASS,
        CCATEGORY,
        CCOMPONENT,
        CCOMPONENT_DIALOG,
        CLIST,
        DIVISION,
        DIVISION_WORDING,
        SCLASS,
        SSUBCLASS,
        SYSTEM,
        SYSTEM_ID,
        SYSTEM_BRAND,
        SYSTEM_DIALOG,
        ASSET_GROUP,
        EFFECT_SCOPE,
        EFFECT_SCOPE_BTN,
        EFFECT_SCOPE_WORDING,
        URGENT_LEVEL,
        URGENT_LEVEL_BTN,
        URGENT_LEVEL_WORDING,
        REQUIRE_RANK,
        ECT,
        EOT,
        ACT,
        PROCESS_PROGRAM
    ),
    INC(
        UNIT_ID,
        USER_NAME,
        UNIT_CATEGORY,
        PHONE,
        EMAIL,
        SUMMARY,
        CONTENT,
        CCLASS,
        CCATEGORY,
        CCOMPONENT,
        CCOMPONENT_DIALOG,
        CLIST,
        EVENT_CLASS,
        EVENT_TYPE,
        EVENT_SECURITY,
        SCLASS,
        SSUBCLASS,
        SYSTEM,
        SYSTEM_ID,
        SYSTEM_BRAND,
        SYSTEM_DIALOG,
        ASSET_GROUP,
        EFFECT_SCOPE,
        EFFECT_SCOPE_BTN,
        EFFECT_SCOPE_WORDING,
        URGENT_LEVEL,
        URGENT_LEVEL_BTN,
        URGENT_LEVEL_WORDING,
        EVENT_PRIORITY,
        EVENTP_RIORITY_WORDING,
        IS_IVR,
        ASSIGN_TIME,
        IS_MAINEVENT,
        MAINEVENT,
        INCFORM_DAILOG,
        INCFORM_DIALOG_BTN,
        EXCLUDE_TIME,
        IS_INTERRUPT,
        ACT,
        IS_SUGGESTCASE,
        INDICATION,
        REASON,
        PROCESS_PROGRAM
    ),
    CHG(
        UNIT_CATEGORY,
        SUMMARY,
        CONTENT,
        EFFECT_SYSTEM,
        CCLASS,
        CCATEGORY,
        CCOMPONENT,
        CCOMPONENT_DIALOG,
        IS_NEWSYSTEM,
        IS_NEWSERVICE,
        IS_URGENT,
        STANDARD,
        CHANGE_TYPE,
        CHANGE_RANK,
        IS_EFFECTFIELD,
        IS_EFFECTACCOUNTANT,
        IS_MODIFYPROGRAM,
        ACT,
        CCT,
        SOLUTION,
        EVALUATION,
        IMPACT_DIALOG_BTN
    ),
    Q_C(
        EOT,
        ECT,
        AST,
        ACT,
        SCLASS,
        SYSTEM,
        SYSTEM_ID,
        SYSTEM_BRAND,
        SYSTEM_DIALOG,
        COUNTERSIGNED_HANDLE
    ),
    SR_C(
        SCLASS,
        SYSTEM,
        SYSTEM_ID,
        SYSTEM_BRAND,
        SYSTEM_DIALOG,
        COUNTERSIGNED_HANDLE
        ),
    INC_C(
        AST,
        ACT,
        SCLASS,
        SYSTEM,
        SYSTEM_ID,
        SYSTEM_BRAND,
        SYSTEM_DIALOG,
        COUNTERSIGNED_HANDLE
    ),
    JOB_AP_C(
        AST,
        SCLASS,
        SYSTEM,
        SYSTEM_ID,
        SYSTEM_BRAND,
        SYSTEM_DIALOG
    ),
    JOB_SP_C(
        SCLASS,
        SYSTEM,
        SYSTEM_ID,
        SYSTEM_BRAND,
        SYSTEM_DIALOG
    ),
    BA(
        EXECUTE_TIME_WORDING,
        DB_IN_USE_WORDING,
        DIVISION
    ),
    KL();

    private String[] columns;

    private EditOneEnum (String... columns) {
        this.columns = columns;
    }
    
    public String[] columns () {
        return this.columns;
    }
    
}
